--DROP TABLE 테이블명 CASCADE CONSTRAINT;


-- Create FM_MENU 
CREATE TABLE FM_MENU
(
   MENUID              NUMBER NOT NULL,
   MENUNAME            VARCHAR2 (40),
   ISROOT              VARCHAR2 (1),
   POSITION            NUMBER,
   MENUTYPE            VARCHAR2 (40),
   PARENTMENUID        NUMBER,
   FM_METADATA         VARCHAR2 (40),
   FM_POLICYMETADATA   VARCHAR2 (40),
   ADMINFLAG           VARCHAR2 (1)
);

ALTER TABLE FM_MENU ADD CONSTRAINT PK_FM_MENU PRIMARY KEY(MENUID);


-- Create FM_METADATA
DROP TABLE FM_METADATA CASCADE CONSTRAINT;

CREATE TABLE FM_METADATA
(
   TABLENAME     VARCHAR2 (40),
   COLUMNNAME    VARCHAR2 (40),
   COLUMNORDER   NUMBER,
   ISKEY         VARCHAR2 (1),
   DATATYPE      VARCHAR2 (40),
   ISREQUIRED    VARCHAR2 (1),
   INPUTTYPE     VARCHAR2 (40),
   SELECTQUERY   VARCHAR2 (2000),
   PARIENTCOLUMNNAME VARCHAR2 (40)
);

ALTER TABLE FM_METADATA ADD CONSTRAINT PK_FM_METADATA PRIMARY KEY(TABLENAME,COLUMNNAME,COLUMNORDER);


CREATE TABLE FM_CREATE_CONSTRAINT
(
   TABLENAME           VARCHAR2(40),
   VALIDATIONQUERY     VARCHAR2 (2000),
   MESSAGE             VARCHAR2 (2000)
);


CREATE TABLE FM_UPDATE_CONSTRAINT
(
   TABLENAME           VARCHAR2(40),
   VALIDATIONQUERY     VARCHAR2 (2000),
   MESSAGE             VARCHAR2 (2000)
);


CREATE TABLE FM_DELETE_CONSTRAINT
(
   TABLENAME           VARCHAR2(40),
   VALIDATIONQUERY     VARCHAR2 (2000),
   MESSAGE             VARCHAR2 (2000)
);



/* Formatted on 2020/04/06 오후 6:28:36 (QP5 v5.227.12220.39754) */
CREATE TABLE FM_MEATADATAHISTORY
(
   HISTORYTABLENAME    VARCHAR2 (40),
   HISTORYCOLUMNNAME   VARCHAR2 (40),
   TABLENAME           VARCHAR2 (40),
   TABLECOLUMNNAME     VARCHAR2 (40),
   OPTIONS             VARCHAR2 (40)
);

ALTER TABLE FM_MEATADATAHISTORY ADD CONSTRAINT PK_FM_MEATADATAHISTORY PRIMARY KEY(HISTORYTABLENAME,HISTORYCOLUMNNAME,TABLENAME);



SET DEFINE OFF;
Insert into FM_MENU
   (MENUID, MENUNAME, ISROOT, POSITION, MENUTYPE, 
    PARENTMENUID, FM_METADATA, ADMINFLAG)
 Values
   (4, 'FM_METADATA', 'N', 2, 'Normal', 
    3, 'FM_METADATA', 'Y');
Insert into FM_MENU
   (MENUID, MENUNAME, ISROOT, POSITION, MENUTYPE, 
    PARENTMENUID, FM_METADATA, ADMINFLAG)
 Values
   (8, 'FM_CREATE_CONSTRAINT', 'Y', 0, 'Normal', 
    3, 'FM_CREATE_CONSTRAINT', 'Y');
Insert into FM_MENU
   (MENUID, MENUNAME, ISROOT, POSITION, MENUTYPE, 
    PARENTMENUID, FM_METADATA, ADMINFLAG)
 Values
   (9, 'FM_UPDATE_CONSTRAINT', 'Y', 0, 'Normal', 
    3, 'FM_UPDATE_CONSTRAINT', 'Y');
Insert into FM_MENU
   (MENUID, MENUNAME, ISROOT, POSITION, MENUTYPE, 
    PARENTMENUID, FM_METADATA, ADMINFLAG)
 Values
   (10, 'FM_DELETE_CONSTRAINT', 'Y', 0, 'Normal', 
    3, 'FM_DELETE_CONSTRAINT', 'Y');
Insert into FM_MENU
   (MENUID, MENUNAME, ISROOT, POSITION, MENUTYPE, 
    PARENTMENUID, FM_METADATA, ADMINFLAG)
 Values
   (11, 'FM_MEATADATAHISTORY', 'Y', 0, 'Normal', 
    3, 'FM_MEATADATAHISTORY', 'Y');
Insert into FM_MENU
   (MENUID, MENUNAME, ISROOT, POSITION, MENUTYPE, 
    PARENTMENUID, FM_METADATA, ADMINFLAG)
 Values
   (7, 'FM_MENU', 'N', 3, 'Normal', 
    3, 'FM_MENU', 'Y');
COMMIT;


SET DEFINE OFF;
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE, 
    INPUTTYPE)
 Values
   ('FM_METADATA', 'TABLENAME', 0, 'Y', 'VARCHAR2', 
    'TEXT');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE, 
    INPUTTYPE)
 Values
   ('FM_METADATA', 'COLUMNNAME', 1, 'Y', 'VARCHAR2', 
    'TEXT');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE, 
    INPUTTYPE)
 Values
   ('FM_METADATA', 'COLUMNORDER', 2, 'Y', 'NUMBER', 
    'TEXT');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE, 
    INPUTTYPE, SELECTQUERY)
 Values
   ('FM_METADATA', 'ISKEY', 3, 'N', 'VARCHAR2', 
    'SELECT', 'SELECT ''Y'' FROM DUAL
UNION 
SELECT ''N'' FROM DUAL');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE, 
    INPUTTYPE, SELECTQUERY)
 Values
   ('FM_METADATA', 'DATATYPE', 4, 'N', 'VARCHAR2', 
    'SELECT', 'SELECT ''VARCHAR'' FROM DUAL
UNION 
SELECT ''NUMBER'' FROM DUAL
UNION 
SELECT ''DATE'' FROM DUAL');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE, 
    INPUTTYPE, SELECTQUERY)
 Values
   ('FM_METADATA', 'ISREQUIRED', 5, 'N', 'VARCHAR2', 
    'SELECT', 'SELECT ''Y'' FROM DUAL WHERE ''Y''=:ISKEY
UNION 
SELECT ''N'' FROM DUAL WHERE ''Y''=:ISKEY');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE, 
    INPUTTYPE, SELECTQUERY)
 Values
   ('FM_METADATA', 'INPUTTYPE', 6, 'N', 'VARCHAR2', 
    'SELECT', 'SELECT ''TEXT'' FROM DUAL
UNION 
SELECT ''SELECT'' FROM DUAL
UNION 
SELECT ''AUTOCOMPLETE'' FROM DUAL');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE, 
    INPUTTYPE)
 Values
   ('FM_METADATA', 'SELECTQUERY', 7, 'N', 'VARCHAR2', 
    'TEXT');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE, 
    INPUTTYPE, SELECTQUERY)
 Values
   ('FM_METADATA', 'PARIENTCOLUMNNAME', 8, 'N', 'VARCHAR2', 
    'SELECT', 'SELECT A.COLUMNNAME FROM FM_METADATA A WHERE A.TABLENAME = :TABLENAME ORDER BY A.COLUMNORDER');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_MENU', 'MENUID', 1, 'Y', 'NUMBER');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_MENU', 'MENUNAME', 2, 'N', 'VARCHAR2');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_MENU', 'ISROOT', 3, 'N', 'VARCHAR2');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_MENU', 'POSITION', 4, 'N', 'NUMBER');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_MENU', 'MENUTYPE', 5, 'N', 'VARCHAR2');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_MENU', 'PARENTMENUID', 6, 'N', 'NUMBER');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE, 
    INPUTTYPE, SELECTQUERY)
 Values
   ('FM_MENU', 'FM_METADATA', 7, 'N', 'VARCHAR2', 
    'SELECT', 'SELECT DISTINCT A.TABLENAME FROM FM_METADATA A');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_MENU', 'FM_POLICYMETADATA', 8, 'N', 'VARCHAR2');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_MENU', 'ADMINFLAG', 9, 'N', 'VARCHAR2');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_CREATE_CONSTRAINT', 'TABLENAME', 1, 'N', 'VARCHAR2');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_CREATE_CONSTRAINT', 'VALIDATIONQUERY', 2, 'N', 'VARCHAR2');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_CREATE_CONSTRAINT', 'MESSAGE', 3, 'N', 'VARCHAR2');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_UPDATE_CONSTRAINT', 'TABLENAME', 1, 'N', 'VARCHAR2');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_UPDATE_CONSTRAINT', 'VALIDATIONQUERY', 2, 'N', 'VARCHAR2');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_UPDATE_CONSTRAINT', 'MESSAGE', 3, 'N', 'VARCHAR2');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_DELETE_CONSTRAINT', 'TABLENAME', 1, 'N', 'VARCHAR2');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_DELETE_CONSTRAINT', 'VALIDATIONQUERY', 2, 'N', 'VARCHAR2');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_DELETE_CONSTRAINT', 'MESSAGE', 3, 'N', 'VARCHAR2');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_MEATADATAHISTORY', 'HISTORYTABLENAME', 1, 'Y', 'VARCHAR2');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_MEATADATAHISTORY', 'HISTORYCOLUMNNAME', 2, 'Y', 'VARCHAR2');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE)
 Values
   ('FM_MEATADATAHISTORY', 'TABLENAME', 3, 'Y', 'VARCHAR2');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE, 
    INPUTTYPE, SELECTQUERY)
 Values
   ('FM_MEATADATAHISTORY', 'TABLECOLUMNNAME', 4, 'N', 'VARCHAR2', 
    'SELECT', 'SELECT A.COLUMNNAME FROM FM_METADATA A WHERE A.TABLENAME=:TABLENAME');
Insert into FM_METADATA
   (TABLENAME, COLUMNNAME, COLUMNORDER, ISKEY, DATATYPE, 
    INPUTTYPE, SELECTQUERY)
 Values
   ('FM_MEATADATAHISTORY', 'OPTIONS', 5, 'N', 'VARCHAR2', 
    'SELECT', 'SELECT ''USERNAME'' FROM DUAL UNION SELECT ''TIMEKEY'' FROM DUAL UNION SELECT ''TIME'' FROM DUAL UNION SELECT ''EVENTNAME'' FROM DUAL');
COMMIT;
